#!/bin/bash

set -e

SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd ${SCRIPT_DIR}

#download antlr if needed
.antlr/download.sh

#run antlr against grump grammar
pushd src/main/antlr
rm -rf *.java *.tokens
java -jar ${SCRIPT_DIR}/.antlr/*.jar GrumpP.g4

#copy to src/main/java/grump with correct package
for g in `ls GrumpP*java`
do
new_g=../java/grumpp/${g}
echo 'package grumpp;' > ${new_g}
cat ${g} >> ${new_g}
done

cp GrumpP.tokens ../java/grump
